services:
  database:
    container_name: libdvd-db
    image: postgres:alpine
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  rustfs:
    container_name: libdvd-s3
    image: rustfs/rustfs:latest
    restart: always
    env_file:
      - ../.env
    ports:
      - "9000:9000"
      - "9001:9001"
